name: Lint Code
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Prettier
      run: yarn format
    - name: Run ESLint
      run: yarn lint
