name: github pages
on:
  push:
    branches:
      - docs/demo # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd example
          sed -i 's/ && yalc publish ..\/packages\/tuya-panel-kit && yalc add tuya-panel-kit --link/ /g' ./package.json
          sed -i 's/"tuya-panel-kit": "link:.yalc\/tuya-panel-kit"/"tuya-panel-kit": "^4.6.2"/g' ./package.json
          yarn install
          yarn build:umi
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/dist
